# Prefix
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Options
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g detach-on-destroy off
set -g repeat-time 1000
set -g mode-keys vi
set -g mouse off

# Panes
set -g pane-border-lines single
set -g pane-border-status off

# Status
set -g status-position bottom
set -g status-justify absolute-centre
set -g status-bg colour0
set -g status-fg colour15

# Sessions
set -g status-left ' #S'
set -g status-left-length 100
set -g status-left-style 'fg=color13'

# Windows
setw -g window-status-current-format '#I:#W '
setw -g window-status-current-style 'fg=colour10 bg=default bold'
setw -g window-status-style 'fg=color11'

# Date and time
set -g status-right '#(date +%%H:%%M) '
set -g status-right-length 0

# Mappings
unbind Left
unbind Right
unbind Up
unbind Down
unbind -n Left
unbind -n Right
unbind -n Up
unbind -n Down
unbind d
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 4
bind -r J resize-pane -D 4
bind -r K resize-pane -U 4
bind -r L resize-pane -R 4
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1
bind "|" split-window -h
bind "\\" split-window -fh
bind "-" split-window -v
bind "_" split-window -fv
bind a previous-window
bind e next-window
bind x kill-window
bind space copy-mode
bind b set-option status
bind -T copy-mode-vi C-j send-keys -X scroll-down
bind -T copy-mode-vi C-k send-keys -X scroll-up
bind r source-file "~/.config/tmux/tmux.conf"
bind f run-shell "tmux neww ~/.config/tmux/sessionizer.sh"
bind g run-shell "~/.config/tmux/versioner.sh"
